### ISSUE TITLE
Usage of dll?

### ISSUE THREAD

**Issue by TomArrow** [thorfdbg/libjpeg#48]
I successfully built the DLL. It didn't export any functions at first, until I added BUILD_LIB to the preprocessor stuff. But all it seems to export now is some Tag-related stuff, not sure what it means.

Is it possible to have a dll that can be used to encode lossless JPEG? If so, what must I do and how would I use it? I'd probably like to use it via interop in C#, but I'd be happy with a normal explanation of how to use it in a normal C/C++ program.

Apologies in advance, I'm a beginner in C++, so some of my questions might seem trivial.

**Comment by thorfdbg** [comment]
It exports that, and hopefully also the jpeg class, defined in interface/jpeg.hpp, which you need also to pull in from your project. The JPEG class is the actual codec. The tag-related stuff is something you need to setup all the parameters because there are too many to put them all into a struct.

Yes, it is certainly possible to encode a lossless JPEG. For that, set JPG_ValueTag(JPGTAG_IMAGE_FRAMETYPE,JPGFLAG_LOSSLESS) and JPG_ValueTag(JPGTAG_MATRIX_LTRAFO,JPGFLAG_MATRIX_COLORTRANSFORMATION_NONE). There is example code included in cmd/encodec.cpp.

**Comment by TomArrow** [comment]
![libjpeg complete exports](https://user-images.githubusercontent.com/6640421/106292985-c3af9500-624d-11eb-8be1-27554df67fc1.png)
I think I did something wrong because I don't get the JPEG class exported, only the tag stuff. See this screenshot of DLL Export Viewer. The JPG_EXPORT also doesn't seem to be in front of those methods. And a comment in jpeg.hpp says:
```This file defines the main entry points and user accessible data for the 10918 (JPEG) codec. Except for the tagitem and hook methods, no other headers should be publically accessible.
```
Which seems in line with what I am seeing.

**Comment by thorfdbg** [comment]
Sorry - this should be fixed now.

**Comment by TomArrow** [comment]
Thanks, but unfortunately I'm still getting the same result. Made sure to delete all the files from all the Release folders and doing a complete recompile. I now see the JPG_EXPORT in front of the class, but I still only have the same 39 functions exported in the dll as before. Does it perhaps need to be added to all the functions?

Again apologies. As I said, I'm very inexperienced and completely out of my depth in this. I might be overlooking or simply not knowing something fundamental.

**Comment by thorfdbg** [comment]
Did you clean all projects of the solution and rebuild the dll project?

**Comment by TomArrow** [comment]
Yes sir, I did. I deleted all the contents of the Release folders in all 4 folders. I also just tried with doing a right-click and "Clean" on each project.

Maybe I should add that I am using Visual Studio 2019 and I updated the VC15 project to v141 Build Tools and the Windows SDK to 10.0.18362.0. Just in case that might play any role. I didn't get any compilation errors or anything though.

**Comment by ValZapod** [comment]
BTW, I also have this problem in VS 2022. At least the dll is very very small.
